### PR TITLE
Updated to kotlin version 1.1.3

### PR DESCRIPTION
**Pull request by wiseman5**

### CODE REVIEW

**Comment by jean79** [comment]
Hi,
good job.
Can you just try to figure out why the qunit tests HtmlBindTest failed?

You will need to update the runner.html:
<script src="../../../target/classes/Yested.js"></script>
<script src="../../../target/test-classes/Yested_test.js"></script>

Then build the project and open this html file from Idea. 
This is not generated correctly: There should be an assert object passed as argument to the tableShouldReflectData* functions
QUnit.test('HtmlBindTest.tableShouldReflectData', function () {
    (new HtmlBindTest()).tableShouldReflectData_masq9t$();
  });
  QUnit.test('HtmlBindTest.tableShouldReflectData_animated', function () {
    (new HtmlBindTest()).tableShouldReflectData_animated_masq9t$();
  });

Eric Pabst designed tests. Maybe he will know how to resolve it.

**Comment by wiseman5** [comment]
I didn't have any tests fail for me.  Which one is failing?  What should I put in the runner.html file?

**Comment by jean79** [comment]
fix the paths in runner.html to generated Yested.js and test file.
Then tests failing are:
HtmlBindTest.tableShouldReflectData
and
HtmlBindTest.tableShouldReflectData_animated (1, 0, 1)
image

**Comment by wiseman5** [comment]
I don't really understand how the classes are getting generated, but it is not consistent.  Sometimes there are lib folders and sometimes there are not.  Sometimes there is a test-classes folder and sometimes there is not.  I compared test-js/Yested-test.js and test-classes/Yested_test.js and they were very similar except Yested_test.js was missing some parameters.  It said "()" instead of "(assert)."  Although, I saw different versions of this class as well when I was experimenting with building and installing, and sometimes there were more things dealing with assert missing and all the tests were failing.

**Comment by epabst** [comment]
@wiseman5 Please squash the 2 commits together.

**Review by epabst — APPROVED** [review]
@wiseman5, Thanks for accepting my changes.

**Comment by epabst** [comment]
@jean79 test-classes/Yested_test.js doesn't end up working.  We need to use Maven to generate that file in order to do the file replacements for the assert parameter, and Maven generates test-js/Yested-tests.js.

**Comment by epabst** [comment]
@wiseman5 I added to the README to explain how the different files are generated.

**Pull request merged**
