### PR TITLE
Update version to avoid confusion with existing yested.

### PR DESCRIPTION
**Pull request by epabst**
https://github.com/jean79/yested has version 0.0.XXX.
This helps prepare yested_fw for release.

### CODE REVIEW

**Review by jean79 — APPROVED** [review]

**Comment by epabst** [comment]
@jean79 I realized that this change will make it so that people can't use yested and yested_fw at the same time, which means that they have to migrate the entire application all at once.  I wonder if we could use a different artifactId.  What is the name yested_fw based on?  Is that a good long-term name?  How about yested-reactive?

**Comment by epabst** [comment]
Another idea is to put all of this yested_fw code into the yested repo with a new major version, possibly in a new kotlin package such as net.yested.reactive, and mark the existing code deprecated.  Then in the next major version we remove the deprecated code.

**Comment by jean79** [comment]
Hi Eric,
I would suggest to keep new version separated as it is now. Let's just use
new major version - 2.0-SNAPSHOT. Merging both version would make it quite
confusing.
I don't think there are many people using the old version of the framework,
do you think?
_fw stands for framework -> not very good i think. Let's use:
net.yested : yested : 2.0.X, ok?
Thanks,
Jan

2017-07-09 5:53 GMT+02:00 Eric Pabst <notifications@github.com>:

**Review by jean79 — APPROVED** [review]

**Comment by epabst** [comment]
@jean79 Seems like it's used quite a bit: https://github.com/search/advanced?q=yested
But I'm ok with that.  Should we rename the yested_fw repo?

**Pull request merged**
